- name: frontend setup
  hosts: all
  tasks:
   - name: installing nginx
     ansible.builtin.dnf:
       name: nginx
       state: present 

## copy a file ansible collection (&) copy a file ansible module

   - name: placlling expense configuration file 
     ansible.builtin.copy:
       src: expense.conf
       dest: /etc/nginx/default.d/expense.conf

## delete file ansible module

   - name: removing onld nginx web content
     ansible.builtin.file:
       path: /usr/share/nginx/html/*
       state: absent

## download and extract ansible module

  #  - name: downloading nginx code
  #    ansible.builtin.unarchive:
  #      src: https://expense-artifacts.s3.amazonaws.com/frontend.zip
  #      dest: /usr/share/nginx/html

# ## download file ansible module

   - name: downloading nginx code
     ansible.builtin.get_url:
       url: https://expense-artifacts.s3.amazonaws.com/frontend.zip
       dest: /usr/share/nginx/html/

## copy file ansible modul


  #  - name: extracting nginx code 
  #  - name: starting nginx server

# echo installing nginx
# dnf install nginx -y &>>$log_file
# stat_check


# echo placlling expense configuration file
# cp expense.conf /etc/nginx/default.d/expense.conf &>>$log_file
# stat_check


# echo removing onld nginx web content
# rm -rf /usr/share/nginx/html/* &>>$log_file
# stat_check



# cd /usr/share/nginx/html &>>$log_file

# download_and_extract() {
#  echo downloading $component code
#  curl -o /tmp/$component.zip https://expense-artifacts.s3.amazonaws.com/$component.zip &>>$log_file
#  stat_check

#  echo extracting $component code
#  unzip /tmp/$component.zip  &>>$log_file
#  stat_check
# }


# echo starting nginx server
# systemctl enable nginx
# systemctl restart nginx