#- name: Frontend Setup
#  hosts: FRONTEND
#  become: true
#  roles:
#    - 01.frontend
#
#- name: myaql Setup
#  hosts: MYSQL
#  become: true
#  roles:
#    - 02.mysql
#
#- name: backend Setup
#  hosts: BACKEND
#  become: true
#  roles:
#    - 03.backend


- name: Frontend Setup
  hosts: FRONTEND
  become: true
  roles:
    - 01.frontend

- name: MySQL Setup
  hosts: MYSQL
  become: true
  roles:
    - 02.mysql

- name: Backend Setup
  hosts: BACKEND
  become: true
  roles:
    - 03.backend

- name: Common Variables Applicable to All Hosts
  hosts: all
  gather_facts: false
  vars:
    user_name: centos
    user_password: DevOps321
