- name: Frontend Setup
  hosts: FRONTEND
  become: true
  roles:
    - frontend

- name: MySQL Setup
  hosts: MYSQL
  become: true
  roles:
    - mysql

- name: Backend Setup
  hosts: BACKEND
  become: true
  roles:
    - backend

- name: Common Variables Applicable to All Hosts
  hosts: all
  gather_facts: false
  vars:
    user_name: centos
    user_password: DevOps321
